---
- name: Install Docker Dependencies
  apt:
    name:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg-agent"
    - "software-properties-common"
    state: present
    install_recommends: yes
    update_cache: yes

- name: Add Docker Repo Key
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    
- name: Run Apt Key Fingreprint
  shell:
    cmd: apt-key fingerprint 0EBFCD88

- name: Adding Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ansible_distribution_release}}" stable
    state: present

- name: Install Docker
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io']
    update_cache: yes
    state: present

- name: ensure docker is running
  service:
    name: docker
    state: started
    enabled: yes

